[build]
builder = "nixpacks"

[deploy]
startCommand = "npx prisma migrate deploy && echo '--- Printing environment variables ---' && printenv && echo '--- Starting application ---' && npm run start:prod"
# healthcheckPath = "/api/health" # Рекомендуется добавить эндпоинт для проверки здоровья
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
