[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && npm run db:migrate && npm run start:prod"
# healthcheckPath = "/api/health" # Рекомендуется добавить эндпоинт для проверки здоровья
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
