[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && npm run db:migrate && npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 