[build]
builder = "nixpacks"

[deploy]
startCommand = "npx prisma migrate deploy && echo 'Container is sleeping for 1 hour for debugging purposes.' && sleep 3600"
# healthcheckPath = "/api/health" # Рекомендуется добавить эндпоинт для проверки здоровья
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
