[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run db:migrate && npm run start:prod"
# healthcheckPath = "/"  # Закомментировать
healthcheckTimeout = 300  # Увеличить с 300 до 600 секунд
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
